package MenusDelConversor;
import javax.swing.JOptionPane;
import OperacionesDelConversorDeTemperatura.Operaciones;

/**
 *
 * @author franklin
 */
public class ConvertidorDeTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorDeTemperatura
     */
    public ConvertidorDeTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboConversorDeTemperatura = new javax.swing.JComboBox<>();
        btnSeleccionar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Elija la temperatura a la que deseas convertir ");

        cboConversorDeTemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Fahrenheit a Celsius", "De Fahrenheit a Kelvin", "De Celsius a Fahrnheit", "De Celsius a Kelvin", "De Kelvin a Fahrenheit", "De Kelvin a Celsius" }));

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboConversorDeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(cboConversorDeTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnVolver))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        Operaciones obj = new Operaciones();
        
        String verificarInput =JOptionPane.showInputDialog("Ingrese la cantidad de temperatura que deseas convertir:");
        int getIndex = cboConversorDeTemperatura.getSelectedIndex();
        
        if(obj.validarNumeros(verificarInput.trim())){
            double cantidadEnTemperatura = Double.parseDouble(verificarInput);
            switch(getIndex){
                case 0,1 -> JOptionPane.showMessageDialog(null,"Fahrenheit: "+ verificarInput + " a " + obj.DeFahrenheit( cantidadEnTemperatura , getIndex) +" " + obj.nombreDeTemperatura(getIndex));
                case 2,3 -> JOptionPane.showMessageDialog(null,"Celsius: " + verificarInput   + " a " + obj.DeCelsius(cantidadEnTemperatura, getIndex)      +" " + obj.nombreDeTemperatura(getIndex));
                case 4,5 -> JOptionPane.showMessageDialog(null, "Kelvin: " + verificarInput   + " a " + obj.DeKelvein(cantidadEnTemperatura, getIndex)      +" " + obj.nombreDeTemperatura(getIndex));
            }
        }else JOptionPane.showMessageDialog(null,"Valor no válido");
        
        
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea continuar?");
       
        switch(opcion){
           case 0 -> volverAlMenuPrincipal();
           case 1, 2 -> {
               JOptionPane.showMessageDialog(null, "Programa finalizado");
               this.dispose();
            }
       }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        volverAlMenuPrincipal();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    public void volverAlMenuPrincipal(){
        MenuPrincipal regresarAlMenuPrincipal = new MenuPrincipal();
        regresarAlMenuPrincipal.setVisible(true);
        this.dispose();
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorDeTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboConversorDeTemperatura;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
